name: Docker Image CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            lotuxpunk/hestia:${{ steps.get_version.outputs.VERSION }}
            lotuxpunk/hestia:latest
            ghcr.io/lotuxpunk/hestia:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/lotuxpunk/hestia:latest
      - name: Upload Release
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/LotuxPunk/Hestia/releases -d '{"tag_name":"${{ steps.get_version.outputs.VERSION }}","target_commitish":"main","name":"${{ steps.get_version.outputs.VERSION }}","draft":false,"prerelease":false,"generate_release_notes":true}'

